[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Optional: redirect all to index.html for SPAs
#[[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200
